### PR TITLE
Add support for plaintext logs

### PR DESCRIPTION
**Pull request by reuvenpo**
This PR adds the `plaintext_log` function to `cosmwasm_std`, as well as all the required support in the runtime and CLI.

Assaf: TODO - We need to apply this patch onto the `stargate` branch.

EDIT 2021-08-09: This PR is now superseded by #811

### CODE REVIEW

**Comment by Mehmetbatmaz** [comment]
Bana niye geliyor bunlar ?

**Review by Mehmetbatmaz — APPROVED** [review]

**Review by Mehmetbatmaz — APPROVED** [review]
Oky
- [ ]

**Review by Cashmaney — APPROVED** [review]

**Review by assafmo — COMMENTED** [review]
Tests?

**Comment by assafmo** [comment]
We need to apply this patch onto the `stargate` branch.

**Pull request closed without merging**
