### PR TITLE
Update SGX driver version in guide

### PR DESCRIPTION
**Pull request by uxt-exe**
Use SGX driver version 2.11.0 from Intel, previously 2.6.0.
Also mention hyperthread disable in BIOS local prep.

### CODE REVIEW

**Comment by toml01** [comment]
Is there any reason not to take the latest version there is for node runners, just like in the "For Developers" section?
i.e. 
```bash
   # 1. Go to https://download.01.org/intel-sgx/sgx-linux
   # 2. Step into the latest version
   # 3. Step into `distro/$LATEST_UBUNTU_YOU_SEE_THERE`
   # 4. Download `sgx_linux_x64_driver_*.bin` and `sgx_linux_x64_sdk_*.bin`
   lynx -dump -listonly -nonumbers https://download.01.org/intel-sgx/sgx-linux/ |
      grep -P 'sgx-linux/(\d\.?)+/' |
      sort -V |
      tail -1 |
      parallel --bar --verbose lynx -dump -listonly -nonumbers "{}/distro" |
      grep -P 'ubuntu\d\d' |
      sort -V |
      tail -1 |
      parallel --bar --verbose lynx -dump -listonly -nonumbers |
      grep -P '\.bin$' |
      parallel --bar --verbose curl -OSs

   # Make the driver and SDK installers executable
   chmod +x ./sgx_linux_*.bin
```

cc @assafmo

**Comment by assafmo** [comment]
Thanks @uxt-exe! :hearts:

**Comment by uxt-exe** [comment]
@toml01 
It's not great to require lynx and parallel packages when they won't be used in the future.
However I did find `https://download.01.org/intel-sgx/latest/linux-latest/distro/`, so something like
```
SGXVERSION=$(curl -s https://download.01.org/intel-sgx/latest/linux-latest/distro/${OS}/driver_readme.txt | sed -n 's/OOT driver:  \(sgx_linux_x64_driver_.*\.bin\)/\1/p')
wget "https://download.01.org/intel-sgx/latest/linux-latest/distro/${OS}/${SGXVERSION}"
```
could work.
Parsing the file list at `linux-latest` is an option, but I think the readme is preferable since the DCAP and OOT files are very similar in naming convention.

**Comment by toml01** [comment]
Makes sense :slightly_smiling_face:

**Pull request merged**
