### PR TITLE
Update install_cli.md

### PR DESCRIPTION
**Pull request by Steven-Chang**
This link doesn't work anymore

### CODE REVIEW

**Comment by reuvenpo** [comment]
I think this is a good replacement for the link.  @assafmo is there a better option?
https://github.com/enigmampc/SecretNetwork/blob/master/docs/validators-and-full-nodes/secretcli.md

**Comment by assafmo** [comment]
> I think this is a good replacement for the link. @assafmo is there a better option?
> https://github.com/enigmampc/SecretNetwork/blob/master/docs/validators-and-full-nodes/secretcli.md

Yes. @Steven-Chang can you use this link instead?

**Comment by Steven-Chang** [comment]
@reuvenpo @assafmo - Hey guys, I updated the link as per your suggestions. Let me know if any issues.
Thanks

**Comment by reuvenpo** [comment]
Looks great, thanks @Steven-Chang !

**Pull request merged**
