### PR TITLE
DOC: fix broken links in governance.md

### PR DESCRIPTION
**Pull request by lacabra**
The title says it all 👋

### CODE REVIEW

**Comment by Cashmaney** [comment]
Thanks for the PR, but in this case I think it isn't a typo, as these docs are uploaded to https://build.scrt.network/light-client-mainnet.html, where they are ordered slightly differently. @jlwaugh can you confirm?

**Comment by lacabra** [comment]
FYI, the links are broken when browsing them on the GitHub repo at `enigmampc/SecretNetwork`

**Comment by assafmo** [comment]
@jlwaugh?

**Comment by assafmo** [comment]
@jlwaugh what should we do with this?

**Comment by mohammedpatla** [comment]
We can bring this PR up in tomorrow's Doc/Dev meeting (12-Aug-2020).
I think its just links broken as the source file was moved to a new location. But have to cross-check with at @jlwaugh

**Comment by assafmo** [comment]
Thank you, Victor! :hearts:

**Pull request merged**
